trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.5.11
      endpoint: github

variables:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.2.300"
  DotNet3Version: "3.0.100-preview6-012264"
  CakeVersion: "0.33.0"
  NuGetVersion: "5.1.0"
  Coverage: "$(Agent.BuildDirectory)/c"
  VstsCoverage: "$(Coverage)"
  Artifacts: $(Build.ArtifactStagingDirectory)
  VstsArtifacts: "$(Artifacts)"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  CodeCovToken: 'b261d715-d42d-4221-acdc-77b28a6d159a'

jobs:
  - template: pipeline/cake.yml@rsg
    parameters:
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      DotNetVersion: $(DotNetVersion)
      DotNet3Version: $(DotNet3Version)
      CakeVersion: $(CakeVersion)
      NuGetVersion: $(NuGetVersion)
