##if SkipSerilog
Logging:
    LogLevel:
        Default: 'Warning'
##endif
##if !SkipSerilog
Serilog:
    MinimumLevel:
        Default: 'Information'
        Override:
            Microsoft: 'Warning'
            Microsoft.AspNetCore.Hosting.Diagnostics: 'Information'
            Microsoft.Hosting.Lifetime: 'Information'
            System: 'Warning'
##endif
